### ISSUE TITLE
安装时显示 解析包时出现问题

### ISSUE THREAD

**Issue by Qing-Novel** [4x-China/AstralCloud#1]
没想到有佬做这个的安卓版，太好了！感谢大佬！不过下载完后安装时不知道为啥无法安装，不知道佬能不能修下？

https://github.com/user-attachments/assets/b9a3e7db-79fc-4342-8da2-3fd7df46436c

**Comment by Spaso1** [comment]
你用的设备类型是什么，华为的吗？
我手头Xiaomi安装成功使用正常，OPPO使用正常
请给我更多信息

**Comment by Spaso1** [comment]
还有您的安卓版本之类的信息

**Comment by Qing-Novel** [comment]
> 你用的设备类型是什么，华为的吗？ 我手头Xiaomi安装成功使用正常，OPPO使用正常 请给我更多信息

是用的华为m6高能版，系统是鸿蒙2，aosp10

**Comment by Qing-Novel** [comment]
我看您安装包内没lib文件夹，就是存放32位和64位文件的文件夹，是不是这个原因呢？

**Comment by Spaso1** [comment]
抱歉，但我写时确实没注意到华为兼容问题，我将会尽快修复这个问题

**Comment by Qing-Novel** [comment]
> 抱歉，但我写时确实没注意到华为兼容问题，我将会尽快修复这个问题

麻烦大佬了

**Comment by Spaso1** [comment]
请你先试试关闭纯净模式，我这边正在研究，不确定是否能完全解决，因为鸿蒙2.0版本有点老，我是用的都是Android12+api而鸿蒙2.0只支持到10

**Comment by Qing-Novel** [comment]
> 请你先试试关闭纯净模式，我这边正在研究，不确定是否能完全解决，因为鸿蒙2.0版本有点老，我是用的都是Android12+api而鸿蒙2.0只支持到10

我是在关闭纯净模式的情况下安装的，我这边用鸿蒙7.2（aosp12）的设备试了下，可以安装，不过不知道为啥无法进入网盘。。。

**Comment by Qing-Novel** [comment]
> > 请你先试试关闭纯净模式，我这边正在研究，不确定是否能完全解决，因为鸿蒙2.0版本有点老，我是用的都是Android12+api而鸿蒙2.0只支持到10
> 
> 我是在关闭纯净模式的情况下安装的，我这边用鸿蒙7.2（aosp12）的设备试了下，可以安装，不过不知道为啥无法进入网盘。。。

粘贴连接后显示读取失败，重进软件后就进入b站手机网页版了。。。

**Comment by Qing-Novel** [comment]
登陆成功了。。。。我用科学上网抓了链接才可以，网盘给的没用

**Comment by Qing-Novel** [comment]
想问下佬，之后会添加状态栏颜色沉浸喝多账户登陆吗？

**Comment by Spaso1** [comment]
好的,我这边用鸿蒙4.2的手机启动,安装正常,第一次启动会有一个文件创建过程,所以需要手动重启,我这边最新已经做成了自动重启,之后就可以更改了,估计晚上9点前提交和发布最新版

**Comment by Qing-Novel** [comment]
> 好的,我这边用鸿蒙4.2的手机启动,安装正常,第一次启动会有一个文件创建过程,所以需要手动重启,我这边最新已经做成了自动重启,之后就可以更改了,估计晚上9点前提交和发布最新版

好的好的，麻烦大佬了，然后大佬，想问下软件ui的按键可以适配下圆角吗？美观度上稍微差了一点
![IMG_20240929_203227](https://github.com/user-attachments/assets/bb4aae9e-2aa7-4ed3-b468-a07ad5f3ba47)

**Comment by Qing-Novel** [comment]
> > 好的,我这边用鸿蒙4.2的手机启动,安装正常,第一次启动会有一个文件创建过程,所以需要手动重启,我这边最新已经做成了自动重启,之后就可以更改了,估计晚上9点前提交和发布最新版
> 
> 好的好的，麻烦大佬了，然后大佬，想问下软件ui的按键可以适配下圆角吗？美观度上稍微差了一点 ![IMG_20240929_203227](https://private-user-images.githubusercontent.com/136884931/371854353-bb4aae9e-2aa7-4ed3-b468-a07ad5f3ba47.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2MTM1MTcsIm5iZiI6MTcyNzYxMzIxNywicGF0aCI6Ii8xMzY4ODQ5MzEvMzcxODU0MzUzLWJiNGFhZTllLTJhYTctNGVkMy1iNDY4LWEwN2FkNWYzYmE0Ny5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOVQxMjMzMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NzE5ODI0OThlZWIwZDE3OGM1YWM4NmQ4NWU2ZjBmNzBiOWU1MWVjZTkyN2NkZjFkNmZlNzI1ODA0ODZmNmU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Gd5bV6VMtJGEKeySf25lFM_6RQ_ZuqM7QcYvuSv5tYI)

![IMG_20240929_203319](https://github.com/user-attachments/assets/9d829d28-c6b9-42ec-b691-7e1d826aabdb)

**Comment by Spaso1** [comment]
> 登陆成功了。。。。我用科学上网抓了链接才可以，网盘给的没用

这个估计不会做,不过UI可能会改

**Comment by Qing-Novel** [comment]
> > 登陆成功了。。。。我用科学上网抓了链接才可以，网盘给的没用
> 
> 这个估计不会做,不过UI可能会改

好的，那麻烦大佬修改UI了，多账号我这边整应用分身解决了

**Comment by Spaso1** [comment]
> > > 登陆成功了。。。。我用科学上网抓了链接才可以，网盘给的没用
> > 
> > 
> > 这个估计不会做,不过UI可能会改
> 
> 好的，那麻烦大佬修改UI了，多账号我这边整应用分身解决了

已经完成UI更新,请下载查看

**Comment by Qing-Novel** [comment]
> > > > 登陆成功了。。。。我用科学上网抓了链接才可以，网盘给的没用
> > > 
> > > 
> > > 这个估计不会做,不过UI可能会改
> > 
> > 
> > 好的，那麻烦大佬修改UI了，多账号我这边整应用分身解决了
> 
> 已经完成UI更新,请下载查看

好的好的我去看看

**Comment by Qing-Novel** [comment]
> > > > 登陆成功了。。。。我用科学上网抓了链接才可以，网盘给的没用
> > > 
> > > 
> > > 这个估计不会做,不过UI可能会改
> > 
> > 
> > 好的，那麻烦大佬修改UI了，多账号我这边整应用分身解决了
> 
> 已经完成UI更新,请下载查看

请问是1.01.3版本吗？

**Comment by Spaso1** [comment]
对,这个包我换源了

**Comment by Qing-Novel** [comment]
> 对,这个包我换源了

好的好的。然后想问下佬，之后会适配aosp10吗？

**Comment by Spaso1** [comment]
未来可能用鸿蒙重构后上架

**Comment by Qing-Novel** [comment]
> 未来可能用鸿蒙重构后上架

好的好的，辛苦作者了
